# Generated by Django 4.2.23 on 2025-06-18 07:04

from django.conf import settings
from django.db import migrations, models
import draft.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default=draft.models.generate_unique_code, max_length=8, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='leagues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
