# Generated by Django 4.2.23 on 2025-06-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draft_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='draft_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='draft_type',
            field=models.CharField(choices=[('snake', 'Snake'), ('auction', 'Auction')], default='snake', max_length=10),
        ),
        migrations.AddField(
            model_name='league',
            name='max_players',
            field=models.PositiveSmallIntegerField(choices=[(2, '2'), (4, '4'), (6, '6'), (8, '8')], default=2),
        ),
        migrations.AddField(
            model_name='league',
            name='region',
            field=models.CharField(choices=[('NACL', 'NACL')], default='NACL', max_length=10),
        ),
    ]
