# Generated by Django 4.2.23 on 2025-06-19 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("draft", "0002_league_draft_date_league_draft_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="league",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_leagues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
