# Generated by Django 4.2.23 on 2025-07-30 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('draft', '0003_league_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_session', to='draft.league')),
                ('ready', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
