# Generated by Django 4.2.23 on 2025-07-31 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_draftsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftsession',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
